unit_idx_to_name = {
    0: "Light Infantry",
    1: "Trooper",
    2: "Engineer",
    3: "Thumper",
    4: "Sardaukar",
    5: "Trike",
    6: "Raider",
    7: "Quad",
    8: "Harvester",
    9: "Atreides Combat Tank",
    10: "Harkonnen Combat Tank",
    11: "Ordos Combat Tank",
    12: "MCV",
    13: "Missile Tank",
    14: "Deviator",
    15: "Siege Tank",
    16: "Sonic Tank",
    17: "Devastator Tank",
    18: "Carryall",
    19: "Carryall2",
    20: "Ornithopter",
    21: "Fremen",
    22: "Fr Non Stealth",
    23: "Saboteur",
    24: "Death Hand Rocket",
    25: "Sandworm",
    26: "Choam Frigate",
    27: "Grenadier",
    28: "Stealth Raider",
    29: "MP Sardaukar"
}

building_idx_to_name = {
    0: "Atreides Construction Yard",
    1: "Harkonnen Construction Yard",
    2: "Ordos Construction Yard",
    3: "Imperial Construction Yard",
    4: "Atreides Concrete",
    5: "Harkonnen Concrete",
    6: "Atreides Concrete",
    7: "Ordos Test Concrete",
    8: "Harkonnen Test Concrete",
    9: "Ordos Test Concrete",
    10: "Atreides Windrap",
    11: "Harkonnen Windrap",
    12: "Ordos Windrap",
    13: "Atreides Barracks",
    14: "Harkonnen Barracks",
    15: "Ordos Barracks",
    16: "Fremen Barracks",
    17: "Atreides Wall",
    18: "Harkonnen Wall",
    19: "Ordos Wall",
    20: "Atreides Refinery",
    21: "Harkonnen Refinery",
    22: "Ordos Refinery",
    23: "Atreides Medium Gun Turret",
    24: "Harkonnen Medium Gun Turret",
    25: "Ordos Medium Gun Turret",
    26: "Atreides Outpost",
    27: "Harkonnen Outpost",
    28: "Ordos Outpost",
    29: "Atreides Large Gun Turret",
    30: "Harkonnen Large Gun Turret",
    31: "Ordos Large Gun Turret",
    32: "Atreides High Tech Factory",
    33: "Harkonnen High Tech Factory",
    34: "Ordos High Tech Factory",
    35: "Atreides Light Factory",
    36: "Harkonnen Light Factory",
    37: "Ordos Light Factory",
    38: "Atreides Silo",
    39: "Harkonnen Silo",
    40: "Ordos Silo",
    41: "Atreides Heavy Factory",
    42: "Harkonnen Heavy Factory",
    43: "Ordos Heavy Factory",
    44: "Mercenary Heavy Factory",
    45: "Imperial Heavy Factory",
    46: "Atreides Starport",
    47: "Harkonnen Starport",
    48: "Ordos Starport",
    49: "Smuggler Starport",
    50: "Atreides Repair Pad",
    51: "Harkonnen Repair Pad",
    52: "Ordos Repair Pad",
    53: "Atreides Research Center",
    54: "Harkonnen Research Center",
    55: "Ordos Research Center",
    56: "Atreides Palace",
    57: "Harkonnen Palace",
    58: "Ordos Palace",
    59: "Imperial Palace",
    60: "Special Harkonnen Outpost",
    61: "Special Ordos Outpost",
}

building_idx_to_name_short = {
    0: "CY",
    1: "CY",
    2: "CY",
    3: "CY",
    4: "Concrt2x2",
    5: "Concrt2x2",
    6: "Concrt2x2",
    7: "Concrt3x3",
    8: "Concrt3x3",
    9: "Concrt3x3",
    10: "Windrap",
    11: "Windrap",
    12: "Windrap",
    13: "Barracks",
    14: "Barracks",
    15: "Barracks",
    16: "Barracks",
    17: "Wall",
    18: "Wall",
    19: "Wall",
    20: "Ref",
    21: "Ref",
    22: "Ref",
    23: "GunTrt",
    24: "GunTrt",
    25: "GunTrt",
    26: "Outpost",
    27: "Outpost",
    28: "Outpost",
    29: "MslTrt",
    30: "MslTrt",
    31: "MslTrt",
    32: "HiTech",
    33: "HiTech",
    34: "HiTech",
    35: "Lit Fac",
    36: "Lit Fac",
    37: "Lit Fac",
    38: "Silo",
    39: "Silo",
    40: "Silo",
    41: "Hvy Fac",
    42: "Hvy Fac",
    43: "Hvy Fac",
    44: "Hvy Fac",
    45: "Hvy Fac",
    46: "Starport",
    47: "Starport",
    48: "Starport",
    49: "Starport",
    50: "RprPad",
    51: "RprPad",
    52: "RprPad",
    53: "Ix",
    54: "Ix",
    55: "Ix",
    56: "Palace",
    57: "Palace",
    58: "Palace",
    59: "Palace",
    60: "Special Outpost",
    61: "Special Outpost",
}

color_idx_to_name = {
    0: "Blue",
    1: "Red",
    2: "Teal",
    3: "Purple",
    4: "Grey",
    5: "Brown",
    6: "Gold",
    7: "LightBrown"
}

color_idx_to_hex_string = {
    0: '#0000FF',
    1: '#FF0000',
    2: '#008080',
    3: "#800080",
    4: "#808080",
    5: "#A52A2A",
    6: "#FFD700",
    7: "#F4A460"
}

# color_idx_to_hex_string = {
#     0: '#6666CC',
#     1: '#FF6666',
#     2: '#66CCCC',
#     3: "#9966FF",
#     4: "#B0B0B0",
#     5: "#B37742",
#     6: "#FFD700",
#     7: "#F4A460"
# }

side_idx_to_name = {
    0: 'Atreides',
    1: 'Harkonnen',
    2: 'Ordos',
    3: 'Emperor',
    4: 'Fremen',
    5: 'Smugglers',
    6: 'Mercenaries',
    7: 'Sandworm'
}

if __name__ == "__main__":
    print(f'{len(unit_idx_to_name)=}')
